dist: xenial
language: rust
branches:
  only:
  - source
install:
  - wget https://github.com/getzola/zola/releases/download/v0.9.0/zola-v0.9.0-x86_64-unknown-linux-gnu.tar.gz -O /tmp/zola.tar.gz
  - mkdir -p bin
  - tar -xvf /tmp/zola.tar.gz -C bin
script:
  - bin/zola build
after_success:
  - sh .travis/push.sh
